"""new migrate instance

Revision ID: 39d0266ccaa3
Revises: 
Create Date: 2021-10-12 21:13:27.776777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d0266ccaa3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('product_brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('product_brand', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('text',
               existing_type=sa.NUMERIC(precision=50),
               nullable=False)

    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('text',
               existing_type=sa.NUMERIC(precision=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.NUMERIC(precision=50),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('product_brand', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.NUMERIC(precision=50),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('product_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    # ### end Alembic commands ###
